{ pkgs, ... }:

{ environment.systemPackages = with pkgs; [     
      linuxKernel.kernels.linux_zen
      linuxKernel.packages.linux_zen.hyperv-daemons 
      linuxKernel.packages.linux_zen.zfs_unstable
      linuxKernel.packages.linux_zen.zenpower
      # linuxKernel.packages.linux_zen.vm-tools
      spice
      spice-autorandr
      spice-gtk
      spice-vdagent
      open-vm-tools
      open-vm-tools-headless
      guestfs-tools
      virglrenderer
      x11spice
      docker-client
      docker
      docker-compose
      docker-machine-kvm2
      x11docker
      podman
      podman-desktop
      skopeo
      buildah
      terminator
      dotnet-sdk
      vscode-with-extensions
      vscodium
      brave
      firefox
      htop
      ranger
      fish
      vim
      wget
      w3m
      dmenu
      neofetch
      neovim
      starship
      bash
      bash-completion
      bashSnippets
      bat
      bazecor
      cargo
      celluloid
      chatterino2
      clang-tools_9
      dunst
      efibootmgr
      elinks
      eww
      feh
      flameshot
      flatpak
      floorp
      fontconfig
      freetype
      fuse-common
      gcc
      gimp
      git
      github-desktop
      gnome.gnome-remote-desktop
      gnome.gnome-keyring
      gnome.networkmanager-openvpn
      gnome.networkmanager-vpnc
      gnomeExtensions.arcmenu
      gnomeExtensions.blur-my-shell
      gnomeExtensions.dash-to-panel
      gnomeExtensions.just-perfection
      gnomeExtensions.openweather
      gnomeExtensions.zen
      gnome.gnome-tweaks
      gnugrep
      gnumake
      gparted
      gnugrep
     # grub2
      hugo
      kitty
      libvirt
      libverto
      looking-glass-client
      luarocks
      lxappearance
      mangohud
      neovim
      networkmanager-openvpn
      nfs-utils
      ninja
      nodejs
      nomacs
      openssl
      os-prober
      OVMFFull
      pavucontrol
      picom
      polkit_gnome
      powershell
      protonup-ng
      python3Full
      python.pkgs.pip
      qemu_full
      ripgrep
      rofi
      steam
      steam-run
      sxhkd
      st
      stdenv
      synergy
      swaycons
      terminus-nerdfont
      tldr
      trash-cli
      tigervnc
      uefi-run
      unzip
      variety
      virtio-win
      virtualgl
      virtualglLib
      virt-manager
      wsl-vpnkit
      xclip
      xdg-desktop-portal-gtk
      xfce.thunar
      xorg.libX11
      xorg.libX11.dev
      xorg.libxcb
      xorg.libXft
      xorg.libXinerama
      xorg.xinit
      xorg.xinput
      xrdp
      zoxide
      zfs
      zfstools
      zfsnap
  ];
}


      

